data:
  data_dir: "data/apples"
  eeg_channels: ['C3_M2', 'C4_M1', 'O1_M2', 'O2_M1']
  eog_channels: ['LOC', 'ROC']
  sleep_stages: ['W', 'N1', 'N2', 'N3', 'R']

static_cca_params:
  is_perform_static_cca: True
  downsampling_factor: 1
  output_dir: "data/static_cca"
  results_dir: "data/static_cca_analysis"

time_cca_params:
  is_perform_time_cca: True
  time_window: 30
  time_step: 10
  output_dir: "data/time_resolved_cca"
  results_dir: "data/time_resolved_cca_analysis"
