run_params:
  run_static_cca: False
  run_time_resolved_cca: False
  run_static_analysis: False
  run_time_resolved_analysis: False
  generate_figures: True

data:
  data_dir: "data/apples"
  eeg_channels: ['C3_M2', 'C4_M1', 'O1_M2', 'O2_M1']
  eog_channels: ['LOC', 'ROC']
  sleep_stages: ['W', 'N1', 'N2', 'N3', 'R']

static_cca_params:
  downsampling_factor: 1
  output_dir: "data/static_cca"
  results_dir: "data/static_cca_analysis"

time_cca_params:
  window_length: 30
  step_length: 15
  output_dir: "data/time_resolved_cca"
  results_dir: "data/time_resolved_cca_analysis"

report:
  figures_folder: "report/figs"
