# visualize_preproc_examples.py
from config_loader import load_config
import matplotlib.pyplot as plt
from logger import logger
import seaborn as sns
import pandas as pd
import sys
import os
import re

"""
Plots raw vs. preprocessed waveforms for EEG/EOG CSVs generated by generate_preproc_examples.py
Expected CSV schema: time_s, raw_uV, preproc_uV
File naming convention used for nicer titles: apples-<subject>_<stage>_<channel>_<dur>s.csv
"""

def create_plot_title(fname: str) -> str:
    base = os.path.basename(fname)
    m = re.match(r"apples-([A-Za-z0-9]+)_([WRN][0-9]?)_([A-Za-z0-9_]+)_(\d+)s\.csv", base)
    if m:
        subject, stage, channel, dur = m.groups()
        return f"{channel} · Stage {stage} · {dur}s (subject {subject})"
    return base

def plot_preproc(csv_path: str, save_path: str):
    try:
        df = pd.read_csv(csv_path)
    except Exception as e:
        logger.error(f"Failed to read CSV: {csv_path} ({e})")
        return
    
    # Only keep first half of the rows
    df = df.iloc[:len(df)//2]

    # Basic column sanity
    required_cols = {"time_s", "raw_uV", "preproc_uV"}
    if not required_cols.issubset(df.columns):
        logger.error(f"CSV {csv_path} missing columns; found {df.columns.tolist()}, expected {sorted(required_cols)}")
        return

    # Style
    sns.set(style="whitegrid")

    # Plot
    plt.figure(figsize=(10, 4.5))
    plt.plot(df["time_s"], df["raw_uV"], label="Raw (µV)", linewidth=1, alpha=0.85)
    plt.plot(df["time_s"], df["preproc_uV"], label="Preprocessed (µV)", linewidth=1, alpha=0.85)

    plt.title(create_plot_title(csv_path))
    plt.xlabel("Time (s)")
    plt.ylabel("Amplitude (µV)")
    plt.legend(loc="upper right", frameon=False)
    plt.tight_layout()
    try:
        plt.savefig(save_path, dpi=300)
        logger.info(f"Saved preprocessing figure: {save_path}")
    except Exception as e:
        logger.error(f"Failed to save figure {save_path}: {e}")
    finally:
        plt.close()

def main():
    
    # Parameters
    config = load_config()
    REPORT_FIGURES_FOLDER = config.report.figures_folder  # "report/figs"
    os.makedirs(REPORT_FIGURES_FOLDER, exist_ok=True)

    # Inputs
    csv_paths = ["data/preproc_examples/apples-160288_N2_C3_M2_30s.csv", 
                 "data/preproc_examples/apples-160288_N2_LOC_30s.csv"] #sys.argv[1:]
    
    if len(csv_paths) == 0:
        logger.error("No input CSVs provided. Usage: python visualize_preprocessing_examples.py <csv1> [<csv2>]")
        return

    figure_names = ["figure6a_preprocessing.png", "figure6b_preprocessing.png"]

    for idx, csv_path in enumerate(csv_paths[:2]):
        out_name = figure_names[idx]
        save_path = os.path.join(REPORT_FIGURES_FOLDER, out_name)
        plot_preproc(csv_path, save_path)

    if len(csv_paths) > 2:
        logger.info("More than two CSVs were provided; only the first two were plotted (figure6a/6b).")

if __name__ == "__main__":
    main()
